<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="listoflist" nsURI="http://example.org/fennec/listoflist/1.0"
    nsPrefix="listoflist">
  <eClassifiers xsi:type="ecore:EClass" name="Config">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputs" upperBound="-1"
        eType="#//StringList"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="StringList" instanceClassName="java.lang.String[]"/>
</ecore:EPackage>
